version: '3.6'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_server
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
    restart: always

  updater:
    build:
      context: .
      dockerfile: Dockerfile_updater
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://test:test@db/test
      FITBIT_CLIENT_ID: 228BZ5
      FITBIT_CLIENT_SECRET: a95774ed9cbb6b29b6132f77bbeb30a3
      STRAVA_CLIENT_ID: 43801
      STRAVA_CLIENT_SECRET: 51cfd621f26e736c47193e9b4cece0d0d216db37
    volumes:
      - ./creds:/usr/src/app/creds
    networks:
      - default
    restart: always

  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
