"""empty message

Revision ID: d56a5d61b3c6
Revises: 
Create Date: 2020-03-25 20:32:33.637060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd56a5d61b3c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitbit_calories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('last_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fitbit_weight',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('record_date', sa.DateTime(), nullable=True),
    sa.Column('record_time', sa.Time(), nullable=True),
    sa.Column('last_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strava_activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('elapsed_time', sa.Float(), nullable=True),
    sa.Column('average_speed', sa.Float(), nullable=True),
    sa.Column('average_cadence', sa.Float(), nullable=True),
    sa.Column('average_heartrate', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('utc_offset', sa.Float(), nullable=True),
    sa.Column('max_speed', sa.Float(), nullable=True),
    sa.Column('max_heartrate', sa.Float(), nullable=True),
    sa.Column('total_elevation_gain', sa.Float(), nullable=True),
    sa.Column('upload_id', sa.BigInteger(), nullable=True),
    sa.Column('moving_time', sa.Float(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('start_date_local', sa.DateTime(), nullable=True),
    sa.Column('last_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strava_activity')
    op.drop_table('fitbit_weight')
    op.drop_table('fitbit_calories')
    # ### end Alembic commands ###
